
title: Jamie Haughton CV
url: 'http://haughters.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jamie Haughton
tagline: Software Engineer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jamieh@ughton.co.uk
#phone: 012 345 6789
 #do not add http://
linkedin: jamie-haughton
github: haughters
#twitter: ''


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
